GET http://localhost:1234/ecr/find/3
###
POST http://localhost:1234/ecr/proposal
Content-Type: application/json

{
    "workshop_name":"Kubernetes",
    "dept_id":1,
    "proposal_by":6001
}

###
GET http://localhost:1234/ecr/authorities/3

###
GET http://localhost:1234/ecr/loadforlevel1/1/6002
###
PUT http://localhost:1234/ecr/acknowledgelevel1/1/6001

###
GET http://localhost:1234/ecr/getacknowledgelevel2/1

###
PUT http://localhost:1234/ecr/acknowedgelevel2/3/12

###
POST http://localhost:1234/login
Content-Type: application/json

{
    "mail":"hod.cse@mec.in",
    "pass":"mec@cs"
}

###

GET http://localhost:1234/seminar/find/1

###

POST http://localhost:1234/seminar/propose
Content-Type: application/json

{
    "seminar_name":"RasberryPy",
    "dept_id":1,
    "proposed_by":6007
}

###
GET http://localhost:1234/seminar/loadforlevel1/1/6001


###

PUT http://localhost:1234/seminar/acknowledgelevel1/1/6001